site_name: ECE/MAE148

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - multirepo:
      cleanup: false
      nav_repos:
        - name: win23team1
          import_url: https://github.com/UCSD-ECEMAE-148/winter-2023-fnal-project-team-1.git?branch=main
          imports: [ /README.md, /images/* ]
        - name: win23team2
          import_url: https://github.com/UCSD-ECEMAE-148/winter-2023-final-project-team-2.git?branch=main
          imports: [ /README.md, /images/* ]
        - name: win23team3
          import_url: https://github.com/UCSD-ECEMAE-148/winter-2023-final-project-team-3.git?branch=main
          imports: [ /README.md, /images/* ]
        - name: win23team4
          import_url: https://github.com/UCSD-ECEMAE-148/winter-2023-final-project-team-4.git?branch=main
          imports: [ /README.md, /images/* ]
        - name: win23team5
          import_url: https://github.com/UCSD-ECEMAE-148/winter-2023-final-project-team-5.git?branch=main
          imports: [ /README.md, /images/* ]
        - name: win23team6
          import_url: https://github.com/UCSD-ECEMAE-148/winter-2023-final-project-team-6.git?branch=main
          imports: [ /README.md, /images/* ]
        - name: win23team7
          import_url: https://github.com/UCSD-ECEMAE-148/winter-2023-final-project-team-7.git?branch=main
          imports: [ /README.md, /images/* ]
        - name: win23team8
          import_url: https://github.com/UCSD-ECEMAE-148/winter-2023-final-project-team-8.git?branch=main
          imports: [ /README.md, /images/* ]
        - name: win23team9
          import_url: https://github.com/UCSD-ECEMAE-148/winter-2023-final-project-team-9.git?branch=main
          imports: [ /README.md, /images/* ]
        - name: win23team12
          import_url: https://github.com/UCSD-ECEMAE-148/winter-2023-final-project-team-12.git?branch=main
          imports: [ /README.md, /images/* ]
        - name: win23team13
          import_url: https://github.com/UCSD-ECEMAE-148/winter-2023-final-project-team-13.git?branch=main
          imports: [ /README.md, /images/* ]
        - name: win23team14
          import_url: https://github.com/UCSD-ECEMAE-148/winter-2023-final-project-team-14.git?branch=main
          imports: [ /README.md, /images/* ]
        - name: win23team15
          import_url: https://github.com/UCSD-ECEMAE-148/winter-2023-final-project-team-15.git?branch=main
          imports: [ /README.md, /images/* ]
        - name: documentation
          import_url: https://github.com/UCSD-ECEMAE-148/documentation.git?branch=main
          imports: [ /Controller/*, /images/* ]
        - name: markdown-documentation
          import_url: https://github.com/UCSD-ECEMAE-148/Markdown-Instructions.git?branch=main
          imports: [ /50-Virtual Machine with DonkeyCar AI Simulator/*, /30-UCSD Robocar Jetson Nano Configuration/*,  /60-OpenCV CUDA Accelerated/*, /100-UCSD Robocar Framework/*, /15-VESC Setup Instructions/*, /ROS2_Guide_Book.pdf, 10-UCSD Robocar ECE & MAE 148/* ]

nav:
  - Documentation:
      - DonkeySimulator: markdown-documentation/50-Virtual Machine with DonkeyCar AI Simulator/50-Virtual Machine and DonkeyCar AI Simulator.md
      - Jetson Initial Setup: markdown-documentation/30-UCSD Robocar Jetson Nano Configuration/30-UCSD Robocar Jetson Nano Configuration.md
      - OpenCV With CUDA Acceleration: markdown-documentation/60doc.md
      - VESC Setup: markdown-documentation/15-VESC Setup Instructions/15-VESC Setup Instructions.md
      - Robocar Setup: markdown-documentation/10-UCSD Robocar ECE & MAE 148/10-UCSD Robocar ECE & MAE 148/10UCSDRobocarECEMAE148.html
      - UCSD Robocar Framework: markdown-documentation/100-UCSD Robocar Framework/100-UCSD Robocar Framework.md
      - ROS2 Guidebook: markdown-documentation/ROS2_Guide_Book.pdf
      - Controller: documentation/Controller/UCSD Robocar Using BetaFPV LiteRadio 3 Pro.md
  - Winter 23:
      - Team 1: win23team1/README.md
      - Team 2: win23team2/README.md
      - Team 3: win23team3/README.md
      - Team 4: win23team4/README.md
      - Team 5: win23team5/README.md
      - Team 6: win23team6/README.md
      - Team 7: win23team7/README.md
      - Team 8: win23team8/README.md
      - Team 9: win23team9/README.md
      - Team 12: win23team12/README.md
      - Team 13: win23team13/README.md
      - Team 14: win23team14/README.md
      - Team 15: win23team15/README.md
